Args = --initialize-at-build-time=org.slf4j \
       --initialize-at-build-time=org.slf4j.LoggerFactory \
       --initialize-at-build-time=org.slf4j.simple.SimpleLoggerFactory \
       --initialize-at-build-time=org.slf4j.helpers.NOP_FallbackServiceProvider \
       --initialize-at-build-time=org.slf4j.helpers.NOPLogger \
       --initialize-at-build-time=org.slf4j.helpers.SubstituteLoggerFactory \
       --initialize-at-build-time=org.slf4j.helpers.BasicMDCAdapter \
       --initialize-at-build-time=org.slf4j.helpers.BasicMarkerFactory \
       --initialize-at-build-time=org.slf4j.MDC \
       --initialize-at-build-time=org.sqlite.util.ProcessRunner \
-H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       --enable-url-protocols=http,https
