Args = --initialize-at-build-time=dev.vatn.cli,dev.vatn.cli.commands \
       --initialize-at-build-time=org.slf4j.LoggerFactory,org.slf4j.simple.SimpleLoggerFactory \
       --initialize-at-build-time=picocli \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       --enable-url-protocols=http,https \
       --no-fallback
